# Generated by Django 6.0.3 on 2026-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='is_free',
            new_name='is_preview',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_display',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
