# Generated by Django 6.0.3 on 2026-04-22 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Masalan: O'zbekistondagi Eng Yaxshi Online Ta'lim Platformasi", max_length=255, verbose_name='Asosiy sarlavha')),
                ('subtitle', models.TextField(help_text='Sarlavha ostidagi tushuntirish matni', verbose_name='Kichik matn')),
                ('courses_count_text', models.CharField(default='6+', max_length=50, verbose_name='Kurslar soni matni')),
                ('students_count_text', models.CharField(default='670+', max_length=50, verbose_name="O'quvchilar soni matni")),
                ('rating_text', models.CharField(default='4.8', max_length=50, verbose_name='Reyting matni')),
                ('background_gradient', models.CharField(default='linear-gradient(90deg, #6A11CB 0%, #2575FC 100%)', max_length=100, verbose_name='Fon gradiyenti (CSS)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner rasmi (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
            ],
            options={
                'verbose_name': 'Asosiy Banner',
                'verbose_name_plural': 'Asosiy Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
